const fs = require('fs');
const path = require('path');

/**
 * Corporate Engine - Deep Initialization Tool (/init-deep)
 * Generates hierarchical AGENTS.md for contextual guidance.
 */

const targetDir = process.cwd();
const maxDepth = parseInt(process.argv[2]) || 2;

console.log(`\n[INIT-DEEP] 🏢 Starting Corporate Knowledge Base Initialization...`);
console.log(`[INIT-DEEP] 📂 Target: ${targetDir} (Max Depth: ${maxDepth})`);

function generateAgentMD(dirPath, depth) {
    if (depth > maxDepth) return;

    const folderName = path.basename(dirPath);
    const files = fs.readdirSync(dirPath);
    const subdirs = files.filter(f => fs.statSync(path.join(dirPath, f)).isDirectory() && !f.startsWith('.') && f !== 'node_modules');

    const content = `# AGENTS Guidelines: ${folderName}

## 📋 Module Overview
- **Location**: \`${path.relative(targetDir, dirPath) || './'}\`
- **Department**: General Engineering / ${folderName.toUpperCase()} Module

## ⚖️ Corporate Standards
1. **Naming**: Follow project-specific conventions identified in the root STANDARDS.md.
2. **Validation**: All changes in this directory MUST pass the \`harness.js\` gate.
3. **Audit**: The QA Lead will cross-check implementation against these local rules.

## 🚫 Local Anti-Patterns
- No hardcoded secrets.
- No direct modification of sibling modules without Architect approval.

## 🔗 Key Files & Dependencies
${files.filter(f => !fs.statSync(path.join(dirPath, f)).isDirectory()).map(f => `- \`${f}\``).join('\n')}

---
*Generated by OMG Corporate Engine /init-deep*
`;

    const filePath = path.join(dirPath, 'AGENTS.md');
    fs.writeFileSync(filePath, content);
    console.log(`[INIT-DEEP] ✅ Generated: ${path.relative(targetDir, filePath)}`);

    subdirs.forEach(sd => generateAgentMD(path.join(dirPath, sd), depth + 1));
}

try {
    generateAgentMD(targetDir, 0);
    console.log(`\n[INIT-DEEP] 🏆 Success: Knowledge Base is now active.`);
} catch (error) {
    console.error(`\n[INIT-DEEP] ❌ Failure: ${error.message}`);
    process.exit(1);
}
