import * as fs from 'fs';
import * as path from 'path';

/**
 * OMG Corporate Engine - Deep Initialization Tool (TypeScript Version)
 */

interface FolderInfo {
    name: string;
    path: string;
    files: string[];
    subdirs: string[];
}

const targetDir = process.cwd();
const maxDepth = parseInt(process.argv[2]) || 2;

console.log(`\n[INIT-DEEP-TS] 🏢 Starting Corporate Knowledge Base Initialization (v2.0)...`);
console.log(`[INIT-DEEP-TS] 📂 Target: ${targetDir} (Max Depth: ${maxDepth})`);

function generateAgentMD(dirPath: string, depth: number): void {
    if (depth > maxDepth) return;

    const folderName = path.basename(dirPath);
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
    
    const info: FolderInfo = {
        name: folderName,
        path: dirPath,
        files: entries.filter(e => e.isFile()).map(e => e.name),
        subdirs: entries.filter(e => e.isDirectory() && !e.name.startsWith('.') && e.name !== 'node_modules').map(e => e.name)
    };

    const content = `# AGENTS Guidelines: ${info.name || 'ROOT'}

## 📋 Module Overview
- **Location**: \`${path.relative(targetDir, dirPath) || './'}\`
- **Department**: Engineering / ${info.name.toUpperCase() || 'CORE'} Module

## ⚖️ Corporate Standards
1. **Type Safety**: Use TypeScript for all new scripts. Ensure strict type definitions.
2. **Validation**: Must pass \`tsx src/harness.ts\`.
3. **Hierarchy**: Follow the Chain of Command defined in root SKILL.md.

## 🔗 Directory Content
${info.files.map(f => `- \`${f}\``).join('\n')}
${info.subdirs.length > 0 ? `\n## 📂 Sub-Modules\n${info.subdirs.map(s => `- \`${s}/\``).join('\n')}` : ''}

---
*Generated by OMG Corporate Engine v2.0 (TypeScript Edition)*
`;

    const filePath = path.join(dirPath, 'AGENTS.md');
    fs.writeFileSync(filePath, content);
    console.log(`[INIT-DEEP-TS] ✅ Generated: ${path.relative(targetDir, filePath)}`);

    info.subdirs.forEach(sd => generateAgentMD(path.join(dirPath, sd), depth + 1));
}

try {
    generateAgentMD(targetDir, 0);
    console.log(`\n[INIT-DEEP-TS] 🏆 Success: Knowledge Base is now active (TS-Ready).`);
} catch (error: any) {
    console.error(`\n[INIT-DEEP-TS] ❌ Failure: ${error.message}`);
    process.exit(1);
}
